# Generated by Django 5.0.2 on 2024-02-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='имя')),
                ('email', models.EmailField(max_length=55, verbose_name='почта')),
                ('comm', models.TextField(verbose_name='Комментарии')),
            ],
        ),
    ]
