# Generated by Django 5.0.2 on 2024-02-18 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментари', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='name',
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100, verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='comments',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='comments',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
